-- MySQL Script generated by MySQL Workbench
-- Fri Jul 10 21:21:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema marqeton
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `marqeton` ;

-- -----------------------------------------------------
-- Schema marqeton
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `marqeton` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `marqeton` ;

-- -----------------------------------------------------
-- Table `marqeton`.`lkp_option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marqeton`.`lkp_option` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `marqeton`.`lkp_option` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `created_on` DATETIME NOT NULL,
  `updated_on` DATETIME NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id` ON `marqeton`.`lkp_option` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name` ON `marqeton`.`lkp_option` (`name` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `marqeton`.`lkp_order_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marqeton`.`lkp_order_status` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `marqeton`.`lkp_order_status` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `created_on` DATETIME NOT NULL,
  `updated_on` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id` ON `marqeton`.`lkp_order_status` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name` ON `marqeton`.`lkp_order_status` (`name` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `marqeton`.`tbl_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marqeton`.`tbl_address` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `marqeton`.`tbl_address` (
  `id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `house_no` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `state` VARCHAR(255) NOT NULL,
  `country` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `address_type` VARCHAR(255) NOT NULL,
  `created_on` DATETIME NOT NULL,
  `postal_code` VARCHAR(255) NOT NULL,
  `street_address` VARCHAR(255) NOT NULL,
  `updated_on` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `tbl_address_fk0`
    FOREIGN KEY (`user_id`)
    REFERENCES `marqeton`.`tbl_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id` ON `marqeton`.`tbl_address` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `tbl_address_fk0` ON `marqeton`.`tbl_address` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `marqeton`.`tbl_banner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marqeton`.`tbl_banner` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `marqeton`.`tbl_banner` (
  `id` BIGINT NOT NULL,
  `created_on` DATETIME NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `status` INT NOT NULL,
  `updated_on` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `marqeton`.`tbl_brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marqeton`.`tbl_brand` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `marqeton`.`tbl_brand` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `created_on` DATETIME NOT NULL,
  `updated_on` DATETIME NOT NULL,
  `discount_percentage` FLOAT NULL DEFAULT NULL,
  `sku` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id` ON `marqeton`.`tbl_brand` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name` ON `marqeton`.`tbl_brand` (`name` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `UK_o4d90mtlyxojx98ot6woad7ng` ON `marqeton`.`tbl_brand` (`sku` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `marqeton`.`tbl_cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marqeton`.`tbl_cart` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `marqeton`.`tbl_cart` (
  `id` BIGINT NOT NULL,
  `product_detail_id` BIGINT NOT NULL,
  `quantity` INT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `created_on` DATETIME NOT NULL,
  `total_price` FLOAT NOT NULL,
  `total_quntity` INT NOT NULL,
  `updated_on` DATETIME NOT NULL,
  `total_quantity` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `tbl_cart_fk0`
    FOREIGN KEY (`product_detail_id`)
    REFERENCES `marqeton`.`tbl_product_detail` (`id`),
  CONSTRAINT `tbl_cart_fk1`
    FOREIGN KEY (`user_id`)
    REFERENCES `marqeton`.`tbl_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id` ON `marqeton`.`tbl_cart` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `tbl_cart_fk0` ON `marqeton`.`tbl_cart` (`product_detail_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `tbl_cart_fk1` ON `marqeton`.`tbl_cart` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `marqeton`.`tbl_cart_product_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marqeton`.`tbl_cart_product_detail` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `marqeton`.`tbl_cart_product_detail` (
  `cart_id` BIGINT NOT NULL,
  `product_detail_id` BIGINT NOT NULL,
  CONSTRAINT `tbl_cart_product_detail_fk0`
    FOREIGN KEY (`cart_id`)
    REFERENCES `marqeton`.`tbl_cart` (`id`),
  CONSTRAINT `tbl_cart_product_detail_fk1`
    FOREIGN KEY (`product_detail_id`)
    REFERENCES `marqeton`.`tbl_product_detail` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `tbl_cart_product_detail_fk0` ON `marqeton`.`tbl_cart_product_detail` (`cart_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `tbl_cart_product_detail_fk1` ON `marqeton`.`tbl_cart_product_detail` (`product_detail_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `marqeton`.`tbl_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marqeton`.`tbl_category` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `marqeton`.`tbl_category` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `category_id` BIGINT NULL DEFAULT NULL,
  `image_url` VARCHAR(500) NULL DEFAULT NULL,
  `status` VARCHAR(255) NOT NULL,
  `created_on` DATETIME NOT NULL,
  `discount_percentage` INT NOT NULL,
  `updated_on` DATETIME NOT NULL,
  `sku` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKqprfa07fy9e8ln5s23ps19m9x`
    FOREIGN KEY (`category_id`)
    REFERENCES `marqeton`.`tbl_category` (`id`),
  CONSTRAINT `tbl_category_fk0`
    FOREIGN KEY (`category_id`)
    REFERENCES `marqeton`.`tbl_category` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id` ON `marqeton`.`tbl_category` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name` ON `marqeton`.`tbl_category` (`name` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `UK_bvpw2nrbe19au9ohae30mjw8s` ON `marqeton`.`tbl_category` (`sku` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `tbl_category_fk0` ON `marqeton`.`tbl_category` (`category_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `marqeton`.`tbl_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marqeton`.`tbl_order` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `marqeton`.`tbl_order` (
  `id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `shipping_address_id` BIGINT NOT NULL,
  `billing_address_id` BIGINT NOT NULL,
  `order_status_id` BIGINT NOT NULL,
  `discount_price` FLOAT NOT NULL,
  `order_date` DATETIME NOT NULL,
  `order_number` VARCHAR(255) NOT NULL,
  `payment_mode` VARCHAR(255) NOT NULL,
  `payment_status` VARCHAR(255) NOT NULL,
  `shipping_charge` FLOAT NOT NULL,
  `total_price` FLOAT NOT NULL,
  `total_weight` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `tbl_order_fk0`
    FOREIGN KEY (`user_id`)
    REFERENCES `marqeton`.`tbl_user` (`id`),
  CONSTRAINT `tbl_order_fk1`
    FOREIGN KEY (`shipping_address_id`)
    REFERENCES `marqeton`.`tbl_address` (`id`),
  CONSTRAINT `tbl_order_fk2`
    FOREIGN KEY (`billing_address_id`)
    REFERENCES `marqeton`.`tbl_address` (`id`),
  CONSTRAINT `tbl_order_fk3`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `marqeton`.`lkp_order_status` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id` ON `marqeton`.`tbl_order` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `tbl_order_fk0` ON `marqeton`.`tbl_order` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `tbl_order_fk1` ON `marqeton`.`tbl_order` (`shipping_address_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `tbl_order_fk2` ON `marqeton`.`tbl_order` (`billing_address_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `tbl_order_fk3` ON `marqeton`.`tbl_order` (`order_status_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `marqeton`.`tbl_order_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marqeton`.`tbl_order_detail` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `marqeton`.`tbl_order_detail` (
  `id` BIGINT NOT NULL,
  `order_id` BIGINT NOT NULL,
  `product_detail_id` BIGINT NOT NULL,
  `order_status_id` BIGINT NOT NULL,
  `created_on` DATETIME NOT NULL,
  `return_date` DATETIME NULL DEFAULT NULL,
  `shipping_date` DATETIME NOT NULL,
  `updated_on` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `tbl_order_detail_fk0`
    FOREIGN KEY (`order_id`)
    REFERENCES `marqeton`.`tbl_order` (`id`),
  CONSTRAINT `tbl_order_detail_fk1`
    FOREIGN KEY (`product_detail_id`)
    REFERENCES `marqeton`.`tbl_product_detail` (`id`),
  CONSTRAINT `tbl_order_detail_fk2`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `marqeton`.`lkp_order_status` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id` ON `marqeton`.`tbl_order_detail` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `tbl_order_detail_fk0` ON `marqeton`.`tbl_order_detail` (`order_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `tbl_order_detail_fk1` ON `marqeton`.`tbl_order_detail` (`product_detail_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `tbl_order_detail_fk2` ON `marqeton`.`tbl_order_detail` (`order_status_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `marqeton`.`tbl_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marqeton`.`tbl_product` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `marqeton`.`tbl_product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `brand_id` BIGINT NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  `created_on` DATETIME NOT NULL,
  `updated_on` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `tbl_product_fk1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `marqeton`.`tbl_brand` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 147
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id` ON `marqeton`.`tbl_product` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `tbl_product_fk1` ON `marqeton`.`tbl_product` (`brand_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `marqeton`.`tbl_product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marqeton`.`tbl_product_category` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `marqeton`.`tbl_product_category` (
  `product_id` BIGINT NOT NULL,
  `category_id` BIGINT NOT NULL,
  CONSTRAINT `tbl_product_category_fk0`
    FOREIGN KEY (`product_id`)
    REFERENCES `marqeton`.`tbl_product` (`id`),
  CONSTRAINT `tbl_product_category_fk1`
    FOREIGN KEY (`category_id`)
    REFERENCES `marqeton`.`tbl_category` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `tbl_product_category_fk0` ON `marqeton`.`tbl_product_category` (`product_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `tbl_product_category_fk1` ON `marqeton`.`tbl_product_category` (`category_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `marqeton`.`tbl_product_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marqeton`.`tbl_product_detail` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `marqeton`.`tbl_product_detail` (
  `id` BIGINT NOT NULL,
  `product_id` BIGINT NOT NULL,
  `stock` INT NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  `actual_price` FLOAT NOT NULL,
  `created_on` DATETIME NOT NULL,
  `discount_price` FLOAT NOT NULL,
  `sku` VARCHAR(255) NOT NULL,
  `updated_on` DATETIME NOT NULL,
  `procured_price` FLOAT NOT NULL,
  `name` VARCHAR(125) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `returnable` INT UNSIGNED NOT NULL,
  `rating` FLOAT NULL DEFAULT NULL,
  `discount_percentage` FLOAT NULL DEFAULT NULL,
  `is_primary` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `tbl_product_detail_fk0`
    FOREIGN KEY (`product_id`)
    REFERENCES `marqeton`.`tbl_product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id` ON `marqeton`.`tbl_product_detail` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `UK_fkj6j4x78mis6a3b4amvt5jhp` USING BTREE ON `marqeton`.`tbl_product_detail` (`sku`) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `tbl_product_detail_fk0` ON `marqeton`.`tbl_product_detail` (`product_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `marqeton`.`tbl_product_multimedia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marqeton`.`tbl_product_multimedia` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `marqeton`.`tbl_product_multimedia` (
  `id` BIGINT NOT NULL,
  `product_detail_id` BIGINT NOT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `video_url` VARCHAR(255) NULL DEFAULT NULL,
  `created_on` DATETIME NOT NULL,
  `updated_on` DATETIME NOT NULL,
  `is_primary` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `tbl_product_multimedia_fk0`
    FOREIGN KEY (`product_detail_id`)
    REFERENCES `marqeton`.`tbl_product_detail` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id` ON `marqeton`.`tbl_product_multimedia` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `tbl_product_multimedia_fk0` USING BTREE ON `marqeton`.`tbl_product_multimedia` (`product_detail_id`) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `marqeton`.`tbl_productdetail_option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marqeton`.`tbl_productdetail_option` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `marqeton`.`tbl_productdetail_option` (
  `product_detail_id` BIGINT NOT NULL,
  `option_id` BIGINT NOT NULL,
  `id` BIGINT NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `unit` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `tbl_productdetail_option_fk0`
    FOREIGN KEY (`product_detail_id`)
    REFERENCES `marqeton`.`tbl_product_detail` (`id`),
  CONSTRAINT `tbl_productdetail_option_fk1`
    FOREIGN KEY (`option_id`)
    REFERENCES `marqeton`.`lkp_option` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `tbl_productdetail_option_fk0` ON `marqeton`.`tbl_productdetail_option` (`product_detail_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `tbl_productdetail_option_fk1` ON `marqeton`.`tbl_productdetail_option` (`option_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `marqeton`.`tbl_review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marqeton`.`tbl_review` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `marqeton`.`tbl_review` (
  `id` BIGINT NOT NULL,
  `product_id` BIGINT NOT NULL,
  `rating` FLOAT NULL DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  `created_on` DATETIME NOT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `updated_on` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `tbl_reviews_fk0`
    FOREIGN KEY (`product_id`)
    REFERENCES `marqeton`.`tbl_product` (`id`),
  CONSTRAINT `tbl_reviews_fk1`
    FOREIGN KEY (`user_id`)
    REFERENCES `marqeton`.`tbl_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id` ON `marqeton`.`tbl_review` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `tbl_reviews_fk0` ON `marqeton`.`tbl_review` (`product_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `tbl_reviews_fk1` ON `marqeton`.`tbl_review` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
